### ISSUE TITLE
Compile failure

### ISSUE THREAD

**Issue by lukemauldinks** [jedisct1/rust-jwt-simple#104]
When using version 0.12.6, a compile on Ubuntu 22.04 fails due to not having cmake and clang installed.  I setup with pure-rust feature and crate still tries to pull in boringssl.

`jwt-simple = { version = "0.12.6", features = ["pure-rust"] }`

**Comment by jedisct1** [comment]
But when you added `features = ["pure-rust"]` because you don't care about speed nor security, did it compile?

**Comment by lukemauldinks** [comment]
When I added that feature, it still did not compile.

**Comment by jedisct1** [comment]
You also need [`default-features=false`](https://github.com/jedisct1/rust-jwt-simple#working-around-compilation-issues-with-the-boring-crate).

**Comment by lukemauldinks** [comment]
I will try it and report back. My application is not sensitive to performance. Are the pure rust libraries insecure?

**Comment by jedisct1** [comment]
They are still a work in progress. BoringSSL is far more mature and serious for production use.
