### ISSUE TITLE
FYI: JWK support in `elliptic-curve` v0.9

### ISSUE THREAD

**Issue by tarcieri** [jedisct1/rust-jwt-simple#14]
Not sure if this is particularly helpful, but heads up: v0.9 of the `elliptic-curve` crate has built-in support for JWK:

https://docs.rs/elliptic-curve/0.9.2/elliptic_curve/struct.JwkEcKey.html

You'll need to use the latest prereleases of the corresponding curve crates (e.g. `p256` v0.8.0-pre) and enable the `jwk` crate feature in order to use it.

**Comment by jedisct1** [comment]
This is great, thanks for the heads up!
