### ISSUE TITLE
Performance degrades on using Vectors over HashSets in validation

### ISSUE THREAD

**Issue by sabify** [jedisct1/rust-jwt-simple#18]
Hello,

Latest changes to validation HashSets (commit and my comment [bdf5662](https://github.com/jedisct1/rust-jwt-simple/commit/bdf5662c8289246ef385c02c87dfeb905c0eb43d#commitcomment-47758903)) will degrade the performance.

Validation over constructing of a set from vector then intersecting have time complexity of O(n^2) and also iterating over vector for searching an item (which `iss` is always a string) has O(n).
Please compare it with intersecting two sets with O(n) and searching an item with O(1).

**Comment by jedisct1** [comment]
Don't speculate, just profile :)

**Comment by sabify** [comment]
How about 10x performance over using `HashSet`s?

```zsh
VerificationOptionsWithVec
                        time:   [356.90 ns 357.60 ns 359.06 ns]
Found 11 outliers among 100 measurements (11.00%)
  4 (4.00%) high mild
  7 (7.00%) high severe

VerificationOptionsWithSet
                        time:   [29.064 ns 29.190 ns 29.336 ns]
Found 11 outliers among 100 measurements (11.00%)
  2 (2.00%) high mild
  9 (9.00%) high severe
```

https://github.com/sabify/rust-jwt-simple/tree/bench
fork and use `cargo bench` under `bench` branch

**Comment by sabify** [comment]
Do you still think we should use vectors?
