### ISSUE TITLE
Take `JWTClaims` as reference, not owned value in `RSAKeyPairLike::sign`

### ISSUE THREAD

**Issue by veeg** [jedisct1/rust-jwt-simple#31]
The current signature of [`RSAKeyPairLike::sign`](https://docs.rs/jwt-simple/0.10.1/jwt_simple/algorithms/trait.RSAKeyPairLike.html#method.sign) requires taking the `JWTClaims` parameter by value, while only being used in [`Token::build`](https://docs.rs/jwt-simple/0.10.1/src/jwt_simple/token.rs.html#87) to serialize to JSON.

This could thus easily only borrow the claims, not consume them.

**Comment by jedisct1** [comment]
Is there a real-world use case where this is an issue, especially since this structure is `Clone`able?

If not, I'd rather avoid a breaking API change. If my memory serves me correctly, this was intentional in order to avoid nonce reuse.

**Comment by veeg** [comment]
I am not entirely certain how I would appropriately model a signing JWT authority, so for _production_ scenario I can't really say. I stumbled across this in by test setup where my generalized structures took a `&T`, when issuing the same generated claims to multiple tests. My workaround was indeed to merely clone it internally.
