### ISSUE TITLE
Consider making `NoCustomClaims` a unit structure.

### ISSUE THREAD

**Issue by veeg** [jedisct1/rust-jwt-simple#33]
Change the definition of `NoCustomClaims` to the following:
```rust
#[derive(...)]
struct NoCustomClaims;
```

This allows the structure to function as a proper marker type isomorphic to the unit type `()`. It also means it can be instantiated without providing the braces. 
```rust
let claims = Claims::with_custom_claims(NoCustomClaim, Duration::from_hours(1);
```

**Comment by jedisct1** [comment]
Unfortunately, this is causing all the tests to fail with 

```text
thread 'tests::require_nonce' panicked at 'called `Result::unwrap()` on an `Err` value: can only flatten structs and maps (got unit struct)', src/lib.rs:447:46
```

So let's keep it as is :)

**Comment by veeg** [comment]
Ahh, That is unfortunate.
