### ISSUE TITLE
Consider PascalCasing `JWTClaims`

### ISSUE THREAD

**Issue by veeg** [jedisct1/rust-jwt-simple#34]
The current casing of `JWTClaims` fully capitalizes the `JWT` portion, while Rust naming conventions suggest following a [PascalCase (documented as UpperCamelCase)](https://rust-lang.github.io/api-guidelines/naming.html#casing-conforms-to-rfc-430-c-case). From what I have generally observed in the Rust ecosystem, abbreviations are treated as separate words, and thus not fully upper-cased. See example from [std](https://doc.rust-lang.org/stable/std/str/struct.Utf8Error.html) and [rocket](https://api.rocket.rs/v0.5-rc/rocket_dyn_templates/handlebars/enum.JsonValue.html).

Suggested name: `JwtClaims`

This probably applies to other types as well, but I also observe that [`RSAPrivateKey` from the `rsa` crate](https://docs.rs/rsa/0.4.0/rsa/struct.RSAPrivateKey.html) keeps a fully capitalized version as well. Personally, the `JWTClaims` was the most jarring.

**Comment by jedisct1** [comment]
That would be a breaking change, with no functional improvement.

While this is uncommon in the Rust world, API stability is something I would really try to guarantee as much as possible, unless there is a strong justification for breaking it.

**Comment by veeg** [comment]
This is the sort of issue one would peg on a `1.0` version milestone or similar, if one agrees with the sentiment of the change. I would not expect an immediate release with non-functional breaking changes.
