### ISSUE TITLE
Consider re-exporting `PublicKeyParts` from `rsa` crate

### ISSUE THREAD

**Issue by veeg** [jedisct1/rust-jwt-simple#35]
Currently, when operating with a `RSAKeyPairLike` instance, e.g., [`RS256KeyPair`](https://docs.rs/jwt-simple/0.10.1/jwt_simple/algorithms/struct.RS256KeyPair.html), it implements a method to get the corresponding internal representation for the public key, [`RS256KeyPair::public_key() -> RS256PublicKey`](https://docs.rs/jwt-simple/0.10.1/jwt_simple/algorithms/struct.RS256KeyPair.html#method.public_key), which in turn implements [`RSAPublicKeyLike`](https://docs.rs/jwt-simple/0.10.1/jwt_simple/algorithms/trait.RSAPublicKeyLike.html). This trait has a [`public_key` method](https://docs.rs/jwt-simple/0.10.1/jwt_simple/algorithms/trait.RSAPublicKeyLike.html#tymethod.public_key) returning the [`rsa::RSAPublicKey`](https://docs.rs/rsa/0.4.0/rsa/struct.RSAPublicKey.html).

This struct in of itself is useless in this context unless you import the appropriate traits from the `rsa` to extract information from the public key, e.g., [`PublicKeyParts`](https://docs.rs/rsa/0.4.0/rsa/trait.PublicKeyParts.html).

This is my current use-case:
```rust
use rsa::PublicKeyParts;

let test_key_pair = RSA256KeyPair::generate(2048)?;
let jwt_public_key = test_key_pair.public_key();
let rsa_public_key = jwt_public_key.public_key().as_ref();

let modulus = base64::encoding_config(rsa_public_key.n().to_bytes_be()), base64::URL_SAFE_NO_PAD);
let exponent  = base64::encoding_config(rsa_public_key.e().to_bytes_be()), base64::URL_SAFE_NO_PAD);
```

It would be optimal if i could use the `rsa` trait(s) from a re-export in `jwt-simple`, since it is so integrated into the crate itself, removing the need for an explicit dependency on `rsa` in consuming crates.

**Comment by jedisct1** [comment]
There's a `from_components()` method in order to create a public key from the exponent and modulus.

Would a `to_components()` returning a serialized representation of these values fit your need?

**Comment by veeg** [comment]
That would indeed fit my use-case. It is the only thing I require from the generated key.

**Comment by jedisct1** [comment]
Done!

I'd rather avoid exposing internal dependencies whose APIs are not stable.
