### ISSUE TITLE
Failure to reject a claim if the processor does not expect the specified audience

### ISSUE THREAD

**Issue by seanpianka** [jedisct1/rust-jwt-simple#40]
I went over a particular section of RFC-7519 regarding processing audiences, and found this section:

> "The "aud" (audience) claim identifies the recipients that the JWT is
   intended for.  Each principal intended to process the JWT MUST
   identify itself with a value in the audience claim.  **If the principal
   processing the claim does not identify itself with a value in the
   "aud" claim when this claim is present, then the JWT MUST be
   rejected.**"

After reviewing the source code for claims validation, it appears that the audiences in the claim are only validated if the `VerificationOptions` specify some audiences: [link](https://github.com/jedisct1/rust-jwt-simple/blob/793d6df3a1244ff729ece7fafbbd0eb21fb928a9/src/claims.rs#L225). Could you confirm that I'm reading this snippet of the spec correctly?

**Comment by seanpianka** [comment]
I pushed a new commit to #41 that modifies the validation logic to reject the claims in the situation described above. The test I added now succeeds, however the `explicitly_empty_audiences` fails at `src/token.rs:221` due to this new change... I'll review the semantics for explicitly empty (but non-None) audiences again soon.

**Comment by veeg** [comment]
The key distinction here is the word process. If this crate serves only the end user side, it is impossible to use this crate for other purposes, e.g., API gateway validations (where all applications are not necessarily known, but the issuer and signing keys are).

If this validation should be required as part of this type, I feel it warrants an entirely different builder, enforcing this through the type system itself.

Imho, I see the current mechanism as preferrable.

**Comment by jedisct1** [comment]
Yes, you can use `options.allowed_audiences = Some([])` to only allow claims with an empty audiences set.

And the API gateway case is a good justification for validation to be optional.
