### ISSUE TITLE
Invalid HS256 JWT Causes Panic via HMAC Verification Function

### ISSUE THREAD

**Issue by janu-cambrelen** [jedisct1/rust-jwt-simple#51]
The `timingsafe_eq` function within the HMAC `verify_token` function panics in some instances.  

> Code reference:
https://github.com/jedisct1/rust-jwt-simple/blob/32feaeb8d061c9b65c063152c4e1199d491ef886/src/algorithms/hmac.rs#L84-L87

### Expected:
`JWTError::InvalidAuthenticationTag`

### Observed:
```
thread 'tokio-runtime-worker' panicked at 'assertion failed: `(left == right)`
  left: `32`,
 right: `33`', .../github.com-1ecc6299db9ec823/jwt-simple-0.10.8/src/common.rs:127:5
```
### Reproduce:
Add a single letter or number to the end of an otherwise valid HS256 JWT.

I experienced the panic after modifying the following token as part of a unit test:

`eyJhbGciOiJIUzI1NiIsImtpZCI6ImEzNTQ2ZDlkLTQ1OGQtNGJlZi05NzJjLTM0OGE5MTIzNWMwNSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDg0Mzk4NzcsImV4cCI6MTY1MTAzMTg3NywibmJmIjoxNjQ4NDM5ODc3fQ.Clj-0BxJ7wIWW0l8BC6ufjyiYakxWe3aPN0hle5jClk`

The aforementioned JWT contains a header that includes a uuid `kid` value and the only claim modified was the `valid_for` duration, but this appears to be immaterial to the observed behavior.

The invalid JWT that caused the panic was the following:

`eyJhbGciOiJIUzI1NiIsImtpZCI6ImEzNTQ2ZDlkLTQ1OGQtNGJlZi05NzJjLTM0OGE5MTIzNWMwNSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDg0Mzk4NzcsImV4cCI6MTY1MTAzMTg3NywibmJmIjoxNjQ4NDM5ODc3fQ.Clj-0BxJ7wIWW0l8BC6ufjyiYakxWe3aPN0hle5jClkz`

Note that the the letter "**z**" (or presumably any other character) appended to the end of the JWT is the only difference between the two.

**Comment by jedisct1** [comment]
Make sure that you are not using an old version.

The `cargo update` command can be used to update your dependencies.

**Comment by janu-cambrelen** [comment]
Awesome!  I started the draft of this issue right before [the change](https://github.com/jedisct1/rust-jwt-simple/commit/a2814a15c7625929b0e804e26cf95feb1cc63abb) went in four days ago.  Thanks for quick response!
