### ISSUE TITLE
High latency on Fastly's Compute@Edge

### ISSUE THREAD

**Issue by StarpTech** [jedisct1/rust-jwt-simple#56]
Hi, I use this package to verify a JWT through JWK's. We experience a double in "CPU time" and an increase in response latency of more than 100% (25ms to 55ms). This is odd. Can anyone experience similar?

This is basically the code we use for that. https://github.com/fastly/compute-rust-auth/blob/main/src/jwt.rs#L8-L40

Version: 0.10.9

**Comment by jedisct1** [comment]
Hi!

And thanks for reporting this.

Can you clarify what if the doubled CPU time is relative to? Is it compared to code compiled for the native architecture?

**Comment by StarpTech** [comment]
Hi @jedisct1 with double I mean the total CPU time with JWT verification and without. The metrics come from the fastly dashboard.

**Comment by jedisct1** [comment]
Verification has a cost, but JWT without verification would be useless.

Looks like you are using RSA which is the slowest option, especially when compiled from Rust to WebAssembly.

If using `HS256`, `HS384` or `HS512` is an option (over RSA) for your application, verification is going to be way faster.

**Comment by StarpTech** [comment]
I mean with "without" that we verify the jwt in one of the upstream services not at the edge. Yes, I suspected something like this. I can't change it easily. Thank you.
