### ISSUE TITLE
Sign method not found

### ISSUE THREAD

**Issue by andrew-j-francis** [jedisct1/rust-jwt-simple#59]
I am running into an error when signing an `RS256KeyPair` with a `Claims` parameter. My code is as follows:

```
let mut key_pair = RS256KeyPair::from_pem(pem_file_contents);
let claims = Claims::create(Duration::from_hours(1))
        .with_issuer(connected_app_consumer_key)
        .with_subject(org_username)
        .with_audience("https://login.salesforce.com");
let token = key_pair.sign(claims);
```

The how-to documentation shows that I can pass a claims object to the sign function but I am receiving the following error:

```
error[E0599]: no method named `sign` found for enum `Result` in the current scope
  --> src\main.rs:26:26
   |
26 |     let token = key_pair.sign(claims);
   |                          ^^^^ method not found in `Result<jwt_simple::algorithms::RS256KeyPair, jwt_simple::Error>`
```

**Comment by jedisct1** [comment]
Did you `use jwt_simple::prelude::*`?

**Comment by jedisct1** [comment]
> method not found in `Result<jwt_simple::algorithms::RS256KeyPair, jwt_simple::Error>`

Ah, no, the issue with your code is that `from_pem()` returns a `Result`. 

When you get a`Result`, you must check whether it is `Ok` or `Err`.

You can use `.unwrap()` or `.expect()` to crash if there was an error, and get the actual value if there was no error:

So instead of:

```rust
let mut key_pair = RS256KeyPair::from_pem(pem_file_contents);
```

you can do:

```rust
let key_pair = RS256KeyPair::from_pem(pem_file_contents).unwrap();
```
