### ISSUE TITLE
Valid tokens misreported as "Not a JWT token"

### ISSUE THREAD

**Issue by andrew-kolesnikov** [jedisct1/rust-jwt-simple#62]
Tokens issued with the following _valid_ header(see https://datatracker.ietf.org/doc/html/rfc9068)   {"typ":"**at+JWT**","alg":"RS256","kid":"RjEwOwOA"} are reported as `Not a JWT token`.

Problem is originating from this `if` here that expects "JWT" but gets "at+JWT":  https://github.com/jedisct1/rust-jwt-simple/blob/master/src/token.rs#L150
`            ensure!(signature_type.to_uppercase() == "JWT", JWTError::NotJWT);
`

**Comment by jedisct1** [comment]
Damn. Why didn't they just use`"JWT"`?

Anyway, 598202744ebf66989e211614860c6a60d4085ce9 should now allow this.

Thanks!

**Comment by andrew-kolesnikov** [comment]
@jedisct1 I would like to thank you for the quick turnaround. I was going to commit a fix, but there's no way it could have been faster than yours :)
