### ISSUE TITLE
There is no way to avoid validating the expiration_at field.

### ISSUE THREAD

**Issue by IsraelZeromski** [jedisct1/rust-jwt-simple#63]
I need the possibility to skip expiration validation.
I’m trying to avoid expiration_date validation having the field set in the serialized token, but it is currently impossible to configure options to avoid that.
Is there a workaround over that?
Thanks in advance.

**Comment by jedisct1** [comment]
If the clock is way off, you can always crank the time tolerance up.

This is the `time_tolerance` value of the validation options.
