### ISSUE TITLE
Update dependecies

### ISSUE THREAD

**Issue by apiraino** [jedisct1/rust-jwt-simple#64]
Hello,

first of all, thanks for this project.

It would be great if this crate could have its dependencies updated, especially the `rsa` crate that in cascade would trigger other crates being updated.

My situation: I use another crate that also depends on a more recent version of `zeroize` and I cannot upgrade it because `jwt_simple` locks to an old version of `zeroize`.

I see some forks of `jwt_simple` tackling this issue so if any volunteer would like to contribute .... :)

thanks

**Comment by apiraino** [comment]
Thanks for sharing your thought on this. I agree it's not an easy task and code changes need to be thoroughly reviewed.

**Comment by jedisct1** [comment]
The [`update-deps`](https://github.com/jedisct1/rust-jwt-simple/tree/update-deps) branch tries to do this.
The `rsa` crate needs an old version of `spki`, so a dependency clash with other crates may still happen, but maybe less frequently than `zeroize`.

There's still one error preventing the crate from compiling:

```
   --> src/algorithms/es256k.rs:159:42
    |
159 |                 self.key_pair().as_ref().sign_digest_with_rng(rng, digest);
    |                                          ^^^^^^^^^^^^^^^^^^^^ the trait `RandomizedDigestSigner<hmac_sha256::Hash, _>` is not implemented for `k256::ecdsa::SigningKey`
    |
    = help: the following other types implement trait `RandomizedDigestSigner<D, S>`:
              <k256::ecdsa::SigningKey as RandomizedDigestSigner<D, ecdsa::Signature<Secp256k1>>>
              <k256::ecdsa::SigningKey as RandomizedDigestSigner<D, k256::ecdsa::recoverable::Signature>>
```

I have no idea what that means and how to fix it. The `k256` code is pretty much a plain copy of `p256` with `p` replaced by `k`, but `p256` compiles fine.

**Comment by jedisct1** [comment]
Or try the current `master`.

I gave up trying to understand and fix the above error, but if you do understand it, I'd love to understand :)

**Comment by sabify** [comment]
They just eased out the trait bounds on `RandomizedDigestSigner` in `k256` crate ([#613](https://github.com/RustCrypto/elliptic-curves/pull/613)). 

You just need to wait for their new version release, `sign_digest_with_rng` will work normally without any modifications for `hmac_sha256::Hash` type.
