### ISSUE TITLE
Remove dependency on clock for platforms where trusted clock is not available (e.g., `x86_64-fortanix-unknown-sgx`)

### ISSUE THREAD

**Issue by gaetanww** [jedisct1/rust-jwt-simple#66]
I'm looking into using `rust-jwt-simple` in systems where no trusted clock is available (e.g., `x86_64-fortanix-unknown-sgx` platform).
ATM, this is not possible, because:
1. `rust-jwt-simple` has a mandatory dependency on `coarsetime` which won't compile on `x86_64-fortanix-unknown-sgx` 
2. The clock is used in `JWTClaims::validate` ([here](https://github.com/jedisct1/rust-jwt-simple/blob/b6a2c5bedddfa3602d89b2e91f9aadce3d1a968d/src/claims.rs#L176)).

Would you consider updating `coarsetime` to support `x86_64-fortanix-unknown-sgx`? Less crucially, I'm wondering if calls to clock::now should be removed for these platform as well, since the clock should not be trusted anyway and this incur additional latency. What do you think?

Happy to submit PRs (on `coarsetime` and `rust-jwt-simple`) if that's of interest.

**Comment by jedisct1** [comment]
Having access to the clock is required both for token verification and for token creation.

I'm not too fond of introducing a hack that would make the same code behave differently on different platforms.

Tokens created without a valid timestamp will not validate with most libraries, including that one on all platforms besides `fortanix`.

And silently ignoring the timestamp on token verification is not consistent with what people would expect on all other platforms, and can be considered a vulnerability.

So... well... I'd rather avoid this.

**Comment by gaetanww** [comment]
Fair enough! I guess this modification on `rust-jwt-simple` would only be an optimization anyway. I'm closing this issue, but the issue on `coarsetime` still seems relevant.
