### ISSUE TITLE
Why does algorithms sign signature include DeserializeOwned? 

### ISSUE THREAD

**Issue by abdo643-HULK** [jedisct1/rust-jwt-simple#69]
I have been looking through the code and was wondering why `CustomClaims` have  `DeserializeOwned` as a trait bound. The claims get only serialized in `Token::build`.`DeserializeOwned` doesn't allow borrowed data, which means we have to make unnecessary allocations.

Thx in advance for the answers

**Comment by jedisct1** [comment]
The reason is to avoid breaking changes in the future. Borrowed data can be a pain, and having owned data gives us less limitations.

If this is a concern, memory allocations can be avoided with `Rc` and `Arc`.
