### ISSUE TITLE
Add features for each algorithm to avoid pulling unnecessary dependencies

### ISSUE THREAD

**Issue by Sytten** [jedisct1/rust-jwt-simple#72]
Hi!
Currently the crate pulls quite a lot of dependencies that are not needed if you use only one type of JWT signature.
It would be super nice if there were a feature for each algorithm.
Thanks!

**Comment by jedisct1** [comment]
I'm totally against that.

Besides compilation time, which shouldn't be an issue for Rust users, what is the downside of defining unused functions?

If you don't use them, the linker should not include them anyway.

Having to turn on flags for every single algorithms makes testing more complicated. It also makes the documentation possibly not match the reality any more. And it introduces duplication and conflicts if multiple dependencies are using the same dependency with different flags.

**Comment by Sytten** [comment]
Pulling in code you dont use is not a really good practice (just security wise) and can easily create conflicts when different versions of dependencies are used by different crates.

Most crates do that just fine and the documentation can tell you which flag to use. On the contrary it creates less conflicts not more.

I really dont get the strong reaction to it. We can reduce the number of flags for sure (rsa, hmac, curve) but I see very little benefit on forcing users to pull in the whole RSA crate and all its dependencies when you use eddcsa...
