### ISSUE TITLE
Don't set the invalid_before field (aka nbf claim) by default

### ISSUE THREAD

**Issue by SylvainGarrigues** [jedisct1/rust-jwt-simple#86]
Is there any rationale why every token generated by this library has a default `nbf` claim? I find this pretty useless / annoying given it is set to the same time than the `iat` claim (i.e. `now()`). I believe the intended use case for this field is to set it in the future.

**Comment by jedisct1** [comment]
It's not the same as the current time.

`invalid_before` is the current time minus the `time_tolerance`.

If a received token is way in the future, something's fishy is going on. Blindly ignoring it can lead to application vulnerabilities later.

**Comment by SylvainGarrigues** [comment]
> It's not the same as the current time.
> 
> `invalid_before` is the current time minus the `time_tolerance`.

https://github.com/jedisct1/rust-jwt-simple/blob/cad828136242e19751f35c77d0f267b3a84119dd/src/claims.rs#L311

Looks like to me `invalid_before` _is_ the current time, no `time_tolerance` involved. Am I missing something?
