### ISSUE TITLE
Extracting arbitrary key from jwt header

### ISSUE THREAD

**Issue by kishansairam9** [jedisct1/rust-jwt-simple#88]
JWT RFC defines the header to be either of JWS or JWE - [reference](https://www.rfc-editor.org/rfc/rfc7519#section-5:~:text=Depending%20upon%0A%20%20%20whether%20the%20JWT%20is%20a%20JWS%20or%20JWE%2C%20the%20corresponding%20rules%20for%20the%20JOSE%0A%20%20%20Header%20values%20apply.)

If we look at RFC for JOSE header in JWS https://www.rfc-editor.org/rfc/rfc7515 - section 4.2, 4.3 it allows aribtrary keys to be defined in jwt header part of payload as long as consumers and producers ensure no collisions in keyspace. 

Don't think it is possible with current Header implementation. It has common fields defined via Serde, but think aribtrary ones will be ignored. Can we add custom option like we do in case of Claims?

**Comment by tazjin** [comment]
This is also required for creating certain JWTs, for example I have a case where a specific additional field is expected in the header and I don't think the library exposes a way to do that at the moment.

**Comment by jedisct1** [comment]
Can that be done without breaking the current API?

**Comment by tazjin** [comment]
I'm pretty sure it can be done only by adding additional public methods, so not removing/changing anything (e.g. adding a `[serde(flatten)]` map to `JWTHeader`, and plumbing through setters for that).

**Comment by jedisct1** [comment]
We can introduce a `TokenWithCustomMetadata` type, but then everything using `Token` may have to be duplicated, and that would become very hard to maintain.

**Comment by jedisct1** [comment]
Unfortunately, that looks too complicated to do.
