### ISSUE TITLE
RSA key size should be configurable

### ISSUE THREAD

**Issue by antonengelhardt** [jedisct1/rust-jwt-simple#91]
Hello,

when trying to create a `RS256PublicKey` using `from_components` (which computes to a 8192-bit-long public key), a `modulus too large` error is caught:

```rust
let algorithm = jwt_simple::algorithms::RS256PublicKey::from_components(&n_dec, &e_dec).unwrap();
```

As we anticipate key sizes to increase in the future, we would like to configure the key size, which is possible using `new_with_size` in the [underlying RSA crate](https://github.com/RustCrypto/RSA/pull/176).

**Comment by jedisct1** [comment]
RSA key sizes are unlikely to increase. RSA 3072 is still considered plenty secure, and a 4096 bit key provides has a stronger security level than AES-256, so going anything beyond that is completely useless.

Accepting arbitrary sizes also instantly opens the protocol to trivial denial of service attacks.

If quantum computers are part of the threat model, RSA would actually need [1 terabyte](keys).

The future is not RSA with bigger keys, it's post-quantum KEMs.
