### ISSUE TITLE
String readable format of HS256 key

### ISSUE THREAD

**Issue by subhrajyoti21** [jedisct1/rust-jwt-simple#92]
I am generating a key by `HS256Key::generate()`. I want to share this key with the service to create jwt for the api call the service is going to make. How do i get a String readable format for the key? Currently, i am trying to create a String by `String::from_utf8_lossy(key.to_bytes())`, however, this gives out unreadable string. Example - "�d�Q�,z�W:���B\r2 ܔ����aZ"

Below is my code: 
```
let key  = HS256Key::generate();
let bytes_k = key.to_bytes();
let s =  String::from_utf8_lossy(&bytes_k);
```

**Comment by jedisct1** [comment]
A key is a sequence of random-looking bits. This is not a password.

If, for some reason, you want it to be a readable string, you can for example encode it in hexadecimal:

```rust
use ct_codecs::{Decoder, Encoder, Hex};
use jwt_simple::reexports::ct_codecs;

fn main() {
    let bin = [1, 2, 3, 4];
    let hex = Hex::encode_to_string(&bin).unwrap();
    let bin_from_hex = Hex::decode_to_vec(&hex, None).unwrap();
}
```
