### ISSUE TITLE
Respect cache control header

### ISSUE THREAD

**Issue by lcmgh** [jedisct1/rust-jwt-simple#95]
Some other JWT libs support auto-refreshing the server keys based on the cache-control header. Is that something worth of being integrated?

**Comment by jedisct1** [comment]
Hi,

I'm not sure I follow. 

`Cache-Control` refers to `HTTP`, but `JWT` and `HTTP` are different things. This library doesn't do any web request nor includes a web server.

**Comment by lcmgh** [comment]
Sorry I assumed this lib does also do web requests.
