### ISSUE TITLE
Could we use optional features to reduce the dependencies?

### ISSUE THREAD

**Issue by photino** [jedisct1/rust-jwt-simple#99]
Our framework [`zino`](https://github.com/photino/zino) is using `jwt-simple`. It is really easy to use. We only rely on the `HS*` algorithms. Could we add features to reduce the dependencies?

**Comment by jedisct1** [comment]
Rust is really bad at optimizing memory usage and code size, but still... if code is not used, it's not going to be included. Dead code elimination is one of the most basic tasks a code generator does, and LLVM is not exception to that.

In this crate, algorithms must be explicitly called via a dedicated entry point. There are no functions that require all the algorithms to be linked. So, if you only use the `HS*` algorithms, other algorithms will not be present in the compiled code.

**Comment by photino** [comment]
Using features can reduce the compile time significantly.
